version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - kikis

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.7.2
    restart: always
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - kikis

  apm:
    hostname: apm
    container_name: apm
    restart: always
    expose:
      - 8200
    image: docker.elastic.co/apm/apm-server:6.7.2
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - kikis

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - kikis
    restart: always

  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgreSQL
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kikis

  aws_stack:
    image: localstack/localstack:latest
    container_name: aws_localstack
    ports:
      - '4568:4568'
      - '4575:4575'
      - '4576:4576'
      - '4569:4569'
      - '8055:8080'
    environment:
      - SERVICES=sns,sqs,kinesis,dynamodb
      - DEBUG=1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:

networks:
  kikis:
    driver: bridge