version: '3'

services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgreSQL
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

volumes:
  db_data:

### Networks Setup ############################################
networks:
  backend:
    driver: "bridge"